server:
  port: 8000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #使服务发现路由
      routes:
        - id: refer-system
          uri: lb://refer-system
          predicates:
            - Path=/api/system/**

  application:
    name: api-gateway